#!/bin/bash

# The easiest of scripts created by BAD Gumby

spath=$(zenity --title 'scrot-gui' --file-selection --save --confirm-overwrite --file-filter="*.png")

if echo "$spath" | grep -q "\.png$"; then
  scrot -s $spath
else
  scrot -s $spath.png
fi
